package ru.itmo.history.PeopleAndMoney.model.domain;

public class Salary {
	//TODO: AutoGenerated
	private long id;
	//TODO: ManyToOne
	private Period period;
	//TODO: ManyToOne
//	private Job job;
	private double salary;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Period getPeriod() {
		return period;
	}

	public void setPeriod(Period period) {
		this.period = period;
	}

//	public Job getJob() {
//		return job;
//	}
//
//	public void setJob(Job job) {
//		this.job = job;
//	}

	public double getSalary() {
		return salary;
	}

	public void setSalary(double salary) {
		this.salary = salary;
	}
}
